/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const MediaFile = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'uploadedAt' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'slug' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'order' : IDL.Int,
  'icon' : IDL.Text,
  'description' : IDL.Text,
  'pricing' : IDL.Text,
  'visible' : IDL.Bool,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Text,
  'review' : IDL.Text,
  'clientImageUrl' : IDL.Text,
  'clientName' : IDL.Text,
  'order' : IDL.Int,
  'rating' : IDL.Nat,
});
export const VideoPlatform = IDL.Variant({
  'instagram' : IDL.Null,
  'upload' : IDL.Null,
  'youtube' : IDL.Null,
});
export const VideoType = IDL.Variant({ 'long' : IDL.Null, 'short' : IDL.Null });
export const VideoEntry = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'duration' : IDL.Nat,
  'thumbnailUrl' : IDL.Text,
  'order' : IDL.Int,
  'views' : IDL.Nat,
  'platform' : VideoPlatform,
  'videoType' : VideoType,
  'category' : IDL.Text,
  'videoUrl' : IDL.Text,
  'uploadDate' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const SectionConfig = IDL.Record({
  'aboutEnabled' : IDL.Bool,
  'heroEnabled' : IDL.Bool,
  'servicesEnabled' : IDL.Bool,
  'shortformEnabled' : IDL.Bool,
  'featuredEnabled' : IDL.Bool,
  'testimonialsEnabled' : IDL.Bool,
  'contactEnabled' : IDL.Bool,
  'longformEnabled' : IDL.Bool,
});
export const SiteContent = IDL.Record({
  'whatsappMessage' : IDL.Text,
  'aboutStat2Label' : IDL.Text,
  'seoTitle' : IDL.Text,
  'heroHeading' : IDL.Text,
  'aboutStat3Value' : IDL.Text,
  'heroName' : IDL.Text,
  'heroButtonLink' : IDL.Text,
  'heroButtonText' : IDL.Text,
  'aboutStat1Value' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'aboutStat3Label' : IDL.Text,
  'logoUrl' : IDL.Text,
  'seoKeywords' : IDL.Text,
  'aboutText' : IDL.Text,
  'viewPortfolioText' : IDL.Text,
  'aboutStat1Label' : IDL.Text,
  'seoDescription' : IDL.Text,
  'faviconUrl' : IDL.Text,
  'aboutStat2Value' : IDL.Text,
  'profileImageUrl' : IDL.Text,
  'aboutSubtext' : IDL.Text,
  'heroTagline' : IDL.Text,
});
export const GlowIntensity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const ThemeSettings = IDL.Record({
  'accentColor' : IDL.Text,
  'darkMode' : IDL.Bool,
  'glowIntensity' : GlowIntensity,
});
export const SearchResult = IDL.Record({
  'services' : IDL.Vec(Service),
  'videos' : IDL.Vec(VideoEntry),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMediaFile' : IDL.Func([MediaFile], [], []),
  'aiProxy' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([Category], [], []),
  'createService' : IDL.Func([Service], [], []),
  'createTestimonial' : IDL.Func([Testimonial], [], []),
  'createVideo' : IDL.Func([VideoEntry], [], []),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteService' : IDL.Func([IDL.Text], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Text], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllMediaFiles' : IDL.Func([], [IDL.Vec(MediaFile)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(VideoEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategory' : IDL.Func([IDL.Text], [Category], ['query']),
  'getMediaFile' : IDL.Func([IDL.Text], [MediaFile], ['query']),
  'getSectionConfig' : IDL.Func([], [SectionConfig], ['query']),
  'getService' : IDL.Func([IDL.Text], [Service], ['query']),
  'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
  'getTestimonial' : IDL.Func([IDL.Text], [Testimonial], ['query']),
  'getThemeSettings' : IDL.Func([], [ThemeSettings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideo' : IDL.Func([IDL.Text], [VideoEntry], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'search' : IDL.Func([IDL.Text], [SearchResult], ['query']),
  'updateCategory' : IDL.Func([IDL.Text, Category], [], []),
  'updateSectionConfig' : IDL.Func([SectionConfig], [], []),
  'updateService' : IDL.Func([IDL.Text, Service], [], []),
  'updateSiteContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateTestimonial' : IDL.Func([IDL.Text, Testimonial], [], []),
  'updateThemeSettings' : IDL.Func([ThemeSettings], [], []),
  'updateVideo' : IDL.Func([IDL.Text, VideoEntry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const MediaFile = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'uploadedAt' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'slug' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Int,
    'icon' : IDL.Text,
    'description' : IDL.Text,
    'pricing' : IDL.Text,
    'visible' : IDL.Bool,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Text,
    'review' : IDL.Text,
    'clientImageUrl' : IDL.Text,
    'clientName' : IDL.Text,
    'order' : IDL.Int,
    'rating' : IDL.Nat,
  });
  const VideoPlatform = IDL.Variant({
    'instagram' : IDL.Null,
    'upload' : IDL.Null,
    'youtube' : IDL.Null,
  });
  const VideoType = IDL.Variant({ 'long' : IDL.Null, 'short' : IDL.Null });
  const VideoEntry = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'duration' : IDL.Nat,
    'thumbnailUrl' : IDL.Text,
    'order' : IDL.Int,
    'views' : IDL.Nat,
    'platform' : VideoPlatform,
    'videoType' : VideoType,
    'category' : IDL.Text,
    'videoUrl' : IDL.Text,
    'uploadDate' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const SectionConfig = IDL.Record({
    'aboutEnabled' : IDL.Bool,
    'heroEnabled' : IDL.Bool,
    'servicesEnabled' : IDL.Bool,
    'shortformEnabled' : IDL.Bool,
    'featuredEnabled' : IDL.Bool,
    'testimonialsEnabled' : IDL.Bool,
    'contactEnabled' : IDL.Bool,
    'longformEnabled' : IDL.Bool,
  });
  const SiteContent = IDL.Record({
    'whatsappMessage' : IDL.Text,
    'aboutStat2Label' : IDL.Text,
    'seoTitle' : IDL.Text,
    'heroHeading' : IDL.Text,
    'aboutStat3Value' : IDL.Text,
    'heroName' : IDL.Text,
    'heroButtonLink' : IDL.Text,
    'heroButtonText' : IDL.Text,
    'aboutStat1Value' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'aboutStat3Label' : IDL.Text,
    'logoUrl' : IDL.Text,
    'seoKeywords' : IDL.Text,
    'aboutText' : IDL.Text,
    'viewPortfolioText' : IDL.Text,
    'aboutStat1Label' : IDL.Text,
    'seoDescription' : IDL.Text,
    'faviconUrl' : IDL.Text,
    'aboutStat2Value' : IDL.Text,
    'profileImageUrl' : IDL.Text,
    'aboutSubtext' : IDL.Text,
    'heroTagline' : IDL.Text,
  });
  const GlowIntensity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ThemeSettings = IDL.Record({
    'accentColor' : IDL.Text,
    'darkMode' : IDL.Bool,
    'glowIntensity' : GlowIntensity,
  });
  const SearchResult = IDL.Record({
    'services' : IDL.Vec(Service),
    'videos' : IDL.Vec(VideoEntry),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMediaFile' : IDL.Func([MediaFile], [], []),
    'aiProxy' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([Category], [], []),
    'createService' : IDL.Func([Service], [], []),
    'createTestimonial' : IDL.Func([Testimonial], [], []),
    'createVideo' : IDL.Func([VideoEntry], [], []),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteService' : IDL.Func([IDL.Text], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Text], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllMediaFiles' : IDL.Func([], [IDL.Vec(MediaFile)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(VideoEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategory' : IDL.Func([IDL.Text], [Category], ['query']),
    'getMediaFile' : IDL.Func([IDL.Text], [MediaFile], ['query']),
    'getSectionConfig' : IDL.Func([], [SectionConfig], ['query']),
    'getService' : IDL.Func([IDL.Text], [Service], ['query']),
    'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
    'getTestimonial' : IDL.Func([IDL.Text], [Testimonial], ['query']),
    'getThemeSettings' : IDL.Func([], [ThemeSettings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideo' : IDL.Func([IDL.Text], [VideoEntry], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'search' : IDL.Func([IDL.Text], [SearchResult], ['query']),
    'updateCategory' : IDL.Func([IDL.Text, Category], [], []),
    'updateSectionConfig' : IDL.Func([SectionConfig], [], []),
    'updateService' : IDL.Func([IDL.Text, Service], [], []),
    'updateSiteContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateTestimonial' : IDL.Func([IDL.Text, Testimonial], [], []),
    'updateThemeSettings' : IDL.Func([ThemeSettings], [], []),
    'updateVideo' : IDL.Func([IDL.Text, VideoEntry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };