/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'id' : string, 'name' : string, 'slug' : string }
export type ExternalBlob = Uint8Array;
export type GlowIntensity = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface MediaFile {
  'id' : string,
  'blob' : ExternalBlob,
  'name' : string,
  'uploadedAt' : Time,
}
export interface SearchResult {
  'services' : Array<Service>,
  'videos' : Array<VideoEntry>,
}
export interface SectionConfig {
  'aboutEnabled' : boolean,
  'heroEnabled' : boolean,
  'servicesEnabled' : boolean,
  'shortformEnabled' : boolean,
  'featuredEnabled' : boolean,
  'testimonialsEnabled' : boolean,
  'contactEnabled' : boolean,
  'longformEnabled' : boolean,
}
export interface Service {
  'id' : string,
  'title' : string,
  'order' : bigint,
  'icon' : string,
  'description' : string,
  'pricing' : string,
  'visible' : boolean,
}
export interface SiteContent {
  'whatsappMessage' : string,
  'aboutStat2Label' : string,
  'seoTitle' : string,
  'heroHeading' : string,
  'aboutStat3Value' : string,
  'heroName' : string,
  'heroButtonLink' : string,
  'heroButtonText' : string,
  'aboutStat1Value' : string,
  'whatsappNumber' : string,
  'aboutStat3Label' : string,
  'logoUrl' : string,
  'seoKeywords' : string,
  'aboutText' : string,
  'viewPortfolioText' : string,
  'aboutStat1Label' : string,
  'seoDescription' : string,
  'faviconUrl' : string,
  'aboutStat2Value' : string,
  'profileImageUrl' : string,
  'aboutSubtext' : string,
  'heroTagline' : string,
}
export interface Testimonial {
  'id' : string,
  'review' : string,
  'clientImageUrl' : string,
  'clientName' : string,
  'order' : bigint,
  'rating' : bigint,
}
export interface ThemeSettings {
  'accentColor' : string,
  'darkMode' : boolean,
  'glowIntensity' : GlowIntensity,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoEntry {
  'id' : string,
  'title' : string,
  'featured' : boolean,
  'duration' : bigint,
  'thumbnailUrl' : string,
  'order' : bigint,
  'views' : bigint,
  'platform' : VideoPlatform,
  'videoType' : VideoType,
  'category' : string,
  'videoUrl' : string,
  'uploadDate' : Time,
}
export type VideoPlatform = { 'instagram' : null } |
  { 'upload' : null } |
  { 'youtube' : null };
export type VideoType = { 'long' : null } |
  { 'short' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMediaFile' : ActorMethod<[MediaFile], undefined>,
  'aiProxy' : ActorMethod<[string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[Category], undefined>,
  'createService' : ActorMethod<[Service], undefined>,
  'createTestimonial' : ActorMethod<[Testimonial], undefined>,
  'createVideo' : ActorMethod<[VideoEntry], undefined>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deleteService' : ActorMethod<[string], undefined>,
  'deleteTestimonial' : ActorMethod<[string], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllMediaFiles' : ActorMethod<[], Array<MediaFile>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getAllVideos' : ActorMethod<[], Array<VideoEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategory' : ActorMethod<[string], Category>,
  'getMediaFile' : ActorMethod<[string], MediaFile>,
  'getSectionConfig' : ActorMethod<[], SectionConfig>,
  'getService' : ActorMethod<[string], Service>,
  'getSiteContent' : ActorMethod<[], SiteContent>,
  'getTestimonial' : ActorMethod<[string], Testimonial>,
  'getThemeSettings' : ActorMethod<[], ThemeSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideo' : ActorMethod<[string], VideoEntry>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'search' : ActorMethod<[string], SearchResult>,
  'updateCategory' : ActorMethod<[string, Category], undefined>,
  'updateSectionConfig' : ActorMethod<[SectionConfig], undefined>,
  'updateService' : ActorMethod<[string, Service], undefined>,
  'updateSiteContent' : ActorMethod<[string, string], undefined>,
  'updateTestimonial' : ActorMethod<[string, Testimonial], undefined>,
  'updateThemeSettings' : ActorMethod<[ThemeSettings], undefined>,
  'updateVideo' : ActorMethod<[string, VideoEntry], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];